import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { atom, useAtom } from "jotai";
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";
import { FaCog } from "react-icons/fa";
import { Clinician, Patient } from "utils/used-types";
import { Metadata } from "next";
import { Providers } from "./providers";
import { getServerAuthSession } from "~/server/auth";
import LogoutButton from "~/components/logout-button";
import DrawerLayout from "~/components/drawer";
type Response = {
  userData: Patient | Clinician | undefined;
  status: string | undefined;
};
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const metadata: Metadata = {
  title: "Hospital CRM",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" data-theme="light">

      <Providers session={session}>
        <body>

          <DrawerLayout>

            {children}
          </DrawerLayout>
        </body>

      </Providers>

    </html>
  );
}


